name = "glm_encrypted_file"
version = "2.0.0"

description = "Read and write encrypted files using openssl shell commands."
licences = ["Apache-2.0"]
repository = { type = "github", user = "toddg", repo = "glm_encrypted_file" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
